### ISSUE TITLE
Can't add games.

### ISSUE THREAD

**Issue by gonggqing** [imjord/Favorite-Games-Launcher#1]
I can't add .exe games into the UI, once I add a .exe file, the file pop up to Desktop.

Here is how I installed:
1. git clone xxx.git
2. npm i 
3. npm run make
4. npm run start 

By the way, what do you mean about "Install NPM packages in both client and server folders" and "Run the start commands in both client and server folders", since I only see the main folder and a sub-folder called "css" in the dir-tree. 
I only run the "npm install" and "start" command in the main folder, is this process caused the "add game" bug?

**Comment by imjord** [comment]
Hello @gonggqing sorry for getting back to late i havent been on github for a while. I'll take a look at this and try to hopefully fix it I had some issues myself with pathing, causing games not to populate. I dont have any promises though because ive not been motivated much lately. As for the "Install NPM packages in both client and server folders"  you are correct I was using a readme template that I have, I have corrected the readme.  I hope all is well and thank you for reporting.

**Comment by imjord** [comment]
@gonggqing issue should be fixed now. Thanks again and Enjoy!

**Comment by gonggqing** [comment]
> @gonggqing issue should be fixed now. Thanks again and E
It works fine! Thanks for your help!

**Comment by gonggqing** [comment]
> @gonggqing issue should be fixed now. Thanks again and Enjoy!

It works fine ! Thanks for your help!
